project:
  type: website

website:
  title: pnw bigfoot sightings
  search: true
  repo-url: https://github.com/edenian-prince/bigfoot-closeread
  repo-actions: [source,edit,issue]

  navbar: 
    background: primary
    left: 
      - text: data
        file: data.qmd
      - text: about
        file: about.qmd
      
    right:
        - icon: github
          href: https://github.com/edenian-prince/bigfoot-closeread
          aria-label: GitHub
